name: Contract Nuget

on:
  push:
    branches:
      - master
    paths:
      - 'src/Obseum.Mluvii.CustomChannel.Contract/**'

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore src/Obseum.Mluvii.CustomChannel.Contract/Obseum.Mluvii.CustomChannel.Contract.csproj

    - name: Build
      run: dotnet build src/Obseum.Mluvii.CustomChannel.Contract/Obseum.Mluvii.CustomChannel.Contract.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack src/Obseum.Mluvii.CustomChannel.Contract/Obseum.Mluvii.CustomChannel.Contract.csproj --no-build --configuration Release /p:PackageVersion=1.${{ github.run_number }} -o nupkg

    # Push NuGet Package
    - name: Push
      run: Get-ChildItem nupkg -Filter *.nupkg | Foreach-Object { dotnet nuget push $_.FullName --source https://nuget.pkg.github.com/ObseumEU/index.json --api-key ${{ secrets.GITHUB_TOKEN  }} --skip-duplicate }
